name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}.Plugin
version: ${project.version}
author: SimSonic
website: http://www.voxile.ru
depend:
  - ProtocolLib
  - LibsDisguises
commands:
  rscd:
    description: ${project.artifactId} command hub
    usage: /<command> do what?
permissions:
  rscd.admin:
    description: Access to all functions
    default: op
